elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt
elmslie-rxjava-2/src/main/java/vivid/money/elmslie/core/ElmStoreCompat.kt
elmslie-samples/android-loader/src/main/java/vivid/money/elmslie/samples/android/loader/elm/Store.kt

Now Actor.execute has the return type Observable<Event>, but in ui implementation it would be more convenient to limit it to Observable<Event.Internal>
@EdKornev, maybe we should add this to the code generator plugin as well?

Allow to return internal events in actor

---

elmslie-android/src/main/java/vivid/money/elmslie/android/base/ElmActivity.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/base/ElmFragment.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/screen/ElmDelegate.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/screen/ElmScreen.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/storeholder/LifecycleAwareStoreHolder.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/storeholder/StoreHolder.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt
elmslie-samples/android-loader/src/main/java/vivid/money/elmslie/samples/android/loader/elm/Store.kt
elmslie-samples/kotlin-calculator/src/main/java/vivid/money/elmslie/samples/calculator/Store.kt
elmslie-store-persisting/build.gradle
elmslie-store-persisting/src/main/AndroidManifest.xml
elmslie-store-persisting/src/main/java/vivid/money/elmslie/storepersisting/ClearableStoreHolder.kt
elmslie-store-persisting/src/main/java/vivid/money/elmslie/storepersisting/RetainedExtentions.kt
elmslie-store-persisting/src/main/java/vivid/money/elmslie/storepersisting/RetainedStoreHolder.kt
elmslie-store-persisting/src/main/java/vivid/money/elmslie/storepersisting/StoreHolders.kt
gradle/dependencies.gradle
settings.gradle

There is one additional module `elmslie-store-persisting` to allow to save store inside ViewModel and reused it later (exactly the same approach that we used inside the main project). I'm not sure about naming, will be glad to advise.
Also, this PR contains one breaking change in a separate commit - I moved Store::start from the factory to StoreHolder (it makes more sense since stop is StoreHolder responsibility).

Store view model persisting

---

build.gradle

Jcenter is dicontinued: https://developer.android.com/studio/build/jcenter-migration
There were no specific jcenter dependencies so the migration is very simple

Migrate from jcenter to maven central

---

elmslie-android/src/main/java/vivid/money/elmslie/android/logger/strategy/Crash.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt

It was possible to call start twice and there was no report about this because we set `isStarted = true` at the end of the start method.

Fix double start reporting issue

---

elmslie-android/src/main/java/vivid/money/elmslie/android/base/ElmActivity.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/base/ElmFragment.kt

LifecycleAwareStoreHolder constructor was always called. In case of overriding storeHolder inside children ElmFragment we still have LifecycleAwareStoreHolder with lifecycleObserver inside base ElmFragment. During onDestroy store.stop() inside was called, it leads to the creation of one more store inside LifecycleAwareStoreHolder additionally to store inside overridden child storeHolder.

Fix parent class StoreHodler initialisation inside ElmActivity and ElmFragment

---

README.md
elmslie-plugin/build.gradle
elmslie-plugin/src/main/kotlin/vivid/money/elmslie/plugin/presentation/PresentationLayerAction.kt
elmslie-plugin/src/main/kotlin/vivid/money/elmslie/plugin/presentation/views/CreatePresentationLayerDialog.kt
elmslie-plugin/src/main/resources/META-INF/plugin.xml
gradle/dependencies.gradle

Code generation plugin didn't work correctly, so this mr:
- Updates intellij plugin to 1.0
- Fixes the plugin
- Adds info about it to the readme
Also, there's a new wiki page about it https://github.com/vivid-money/elmslie/wiki/Code-generation-plugin-for-Android-Studio
Plugin is now available at https://plugins.jetbrains.com/plugin/17176-elmslie-generator/versions/stable/125661

Fix plugin for code generation

---

elmslie-android/src/main/java/vivid/money/elmslie/android/screen/ElmScreen.kt

Now, in case of using retain store holder init event will be sent every time the screen receives an onCreate event. This is not the intended behavior, because most of the time init is supposed to start subscriptions which should happen only once

Send init event only once in store lifecycle

---

elmslie-core/src/main/java/vivid/money/elmslie/core/store/Store.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/binding/ConversationRules.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/binding/ConversionContract.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/binding/Coordination.kt
elmslie-core/src/test/java/vivid/money/elmslie/core/store/ElmStoreWithChildTest.kt
elmslie-core/src/test/java/vivid/money/elmslie/core/testutil/model/ParentModels.kt

This merge request enables a new approach for defining communication between stores
The current implementation has some disadvantages:
-  Limits communication possibilities
Only event to event and effect to effect mappings
- Has strict contract
Events are mapped without state and effects may access parent state
- Defines strict parent - child relationship
Instead of making stores as indepent as possible
- Allows to access internal implementation details
Events by nature contain a private store information. Internal events are named this way obviously  to represent **internal events**
- There's no way to trigger an event in the parent from the child store
There are other possibilities to workaround this, but it seems like the right time to make this change.
The case which lead to this …

Store coordination (Conversation rules) 

---

elmslie-core/src/main/java/vivid/money/elmslie/core/store/EffectsBuffer.kt

Our most common crash happened because of class cast exceptions inside NotificationLite.java:190 (ReplaySubject.java:782) after restoring fragments from the background. 
Classes were obfuscated and I failed to reproduce this issue. But during reviewing sources I noticed that we call subject.onNext from computation threads and call onComplete from the main thread. And the last object inside the ReplaySubject queue wasn't a complete event, but some live event. I assume that it can be fixed by making ReplaySubject serialized.
<details open>
<summary>Crash log</summary>
```
io.reactivex.rxjava3.internal.util.NotificationLite.getError (NotificationLite.java:190)
io.reactivex.rxjava3.subjects.ReplaySubject$UnboundedReplayBuffer.replay (ReplaySubject.java:782) …
```

Make effects buffer's replay subject serialized

---

elmslie-android/src/main/java/vivid/money/elmslie/android/screen/ElmScreen.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/EffectsBuffer.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/Store.kt
elmslie-core/src/test/java/vivid/money/elmslie/core/store/EffectsBufferTest.kt
elmslie-core/src/test/java/vivid/money/elmslie/core/store/ElmStoreWithChildTest.kt
elmslie-core/src/test/java/vivid/money/elmslie/core/testutil/model/ParentModels.kt

The issue can be described as "Parent effects are getting lost before they are observed by ElmScreen".  
This was happening because of the encapsulated behavior of `EffectsBuffer` to stop buffering upon first subscription. But the first subscription was done by the store coordination thus effects were lost. This PR is to fix it.

Fix Effects Coordination

---

.github/sh/validate_main_branch.sh
.github/sh/validate_publishing_branch.sh
.github/workflows/release-plugin.yml
.github/workflows/release.yml

This merge request allows to publish library releases for branches starting with `publish`.

Allow to publish from other branches

---

elmslie-samples/android-loader/src/main/AndroidManifest.xml
elmslie-samples/android-loader/src/main/res/xml/disable_backup.xml
elmslie-samples/compose-paging/src/main/AndroidManifest.xml
elmslie-samples/compose-paging/src/main/res/xml/disable_backup.xml

Add support for new backup rules, because`android:allowBackup="false"` is deprecated

Support android 12 backup rules

---

elmslie-samples/android-loader/build.gradle
elmslie-samples/android-loader/src/androidTest/java/vivid/money/elmslie/samples/android/loader/MainScreen.kt
elmslie-samples/android-loader/src/androidTest/java/vivid/money/elmslie/samples/android/loader/MainScreenTest.kt
elmslie-samples/android-loader/src/androidTest/java/vivid/money/elmslie/samples/android/loader/scenario/ErrorStateScenario.kt
elmslie-samples/android-loader/src/androidTest/java/vivid/money/elmslie/samples/android/loader/scenario/LoadingScreenScenario.kt
elmslie-samples/android-loader/src/androidTest/java/vivid/money/elmslie/samples/android/loader/scenario/NumberStateScenario.kt
elmslie-samples/android-loader/src/main/java/vivid/money/elmslie/samples/android/loader/repository/ValueRepository.kt
gradle/dependencies.gradle

This merge requests adds very basic ui tests for `android-loader` sample to verify library integrity before releases. Right now the tests should be run locally and manually before every release.

Add basic UI tests

---

elmslie-test-rxjava-3/build.gradle
elmslie-test/build.gradle
gradle/android-publishing.gradle

Fix missed elmslie-test and elmslie-test-rxjava3 artifacts in Jitpack.
I'm not sure that it should work like this for publishing to Jitpack, but at least these artifacts appear in maven locals after `publishToMavenLocal`

Fix test libs releases

---

elmslie-rxjava-3/src/main/java/vivid/money/elmslie/core/MappingActorCompat.kt

1.4.0 version `mapErrorEvent` don't omit successful events. It mapped errors inside onErrorReturns but don't change successful flow behavior.

Make Rxjava3 Mapping ActorCompat mapErrorEvent don't hide successful events

---

elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt

Just missed call break backward compatibility.

Add event listener calls to event dispatching

---

elmslie-android/src/main/java/vivid/money/elmslie/android/screen/ElmScreen.kt

A good example is when a store reduces event and produce two effects. With the current implementation, only one will be processed. I believe that we don't need to use `postSingle` for effects.

Fix missed effects

---

elmslie-android/src/main/java/vivid/money/elmslie/android/renderer/ElmRenderer.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/switcher/Switcher.kt
elmslie-samples/coroutines-loader/build.gradle
elmslie-samples/coroutines-loader/src/main/java/vivid/money/elmslie/samples/coroutines/timer/MainActivity.kt
elmslie-samples/coroutines-loader/src/main/java/vivid/money/elmslie/samples/coroutines/timer/MainFragment.kt
elmslie-samples/coroutines-loader/src/main/java/vivid/money/elmslie/samples/coroutines/timer/elm/StoreFactory.kt
elmslie-samples/coroutines-loader/src/main/java/vivid/money/elmslie/samples/coroutines/timer/elm/TimerActor.kt
elmslie-samples/coroutines-loader/src/main/java/vivid/money/elmslie/samples/coroutines/timer/elm/TimerModels.kt
elmslie-samples/coroutines-loader/src/main/res/layout/activity_main.xml
elmslie-samples/coroutines-loader/src/main/res/layout/fragment_main.xml
gradle/dependencies.gradle

When the flow inside `Switcher` throws exceptions sometimes it may cancel the whole scope and this error is not handling by `mapEvents` method. This leads to unexpected behavior and loose events for reducing. It can be reproduced in the sample app from this repository (coroutines-loader).
The exception which can be thrown and breaks the flow:
```
at vivid.money.elmslie.samples.coroutines.timer.elm.TimerActor$secondsFlow$1.invokeSuspend(TimerActor.kt:31)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at …
```

fix Switcher + rewrite one example

---

elmslie-android/src/main/java/vivid/money/elmslie/android/renderer/ElmRenderer.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/renderer/ElmRendererDelegate.kt
samples/coroutines-loader/src/main/java/vivid/money/elmslie/samples/coroutines/timer/MainFragment.kt

For now, the most dirty place is a creation connection between store and Fragment/Activity, for several reasons:
- we have to create unused property inside (render), and suppress 'this' reference
- the property forces users use the single store for all the UI and restricts to create multiple parallel ones. (except Compose)
This PR attempts to tackle this constraint, so users will be able to create implementations of the `ElmRendererDelegate`, with passing inside some parts of the UI.
Roughly, it can be done with the following way:
```
class MapDelegate(
val map: MapBinding,
): ElmRendererDelegate {
val mapStore by elmStoreWithRenderer()
override fun render(state: MapState) {
map.bind(state)
}
}
```
These delegates are placed inside Fragment/Activity.
In addition, the initial phase …

Redesigned initialization elm store with renderer for fragment/activity

---

elmslie-android/src/main/java/vivid/money/elmslie/android/ElmStoreLazy.kt
elmslie-android/src/main/java/vivid/money/elmslie/android/renderer/ElmRenderer.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/config/ElmslieConfig.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/EffectCachingElmStore.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/ElmStore.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/Store.kt
elmslie-core/src/main/java/vivid/money/elmslie/core/store/StoreListener.kt

You can add listeners on 3 lvls:
- global listeners in Elmslie config
- in-store constructor
- in runtime with attach/deatachListener store methods (not thread safe)
Closes https://github.com/vivid-money/elmslie/issues/207

Store listeners

---

elmslie-android/src/main/kotlin/money/vivid/elmslie/android/renderer/ElmRenderer.kt
elmslie-core/api/elmslie-core.api
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/ElmScope.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/config/ElmslieConfig.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/store/Actor.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/store/ElmStore.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/store/Store.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/switcher/Switcher.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/utils/DispatcherProvider.kt
elmslie-core/src/commonTest/kotlin/money/vivid/elmslie/core/store/EffectCachingElmStoreTest.kt
elmslie-core/src/commonTest/kotlin/money/vivid/elmslie/core/store/ElmStoreTest.kt
elmslie-core/src/commonWebMain/kotlin/money/vivid/elmslie/core/utils/DispatcherProvider.kt
elmslie-core/src/jvmMain/kotlin/money/vivid/elmslie/core/utils/DispatcherProvider.kt
elmslie-core/src/nativeMain/kotlin/money/vivid/elmslie/core/utils/DispatcherProvider.kt
samples/kotlin-calculator/src/test/kotlin/money/vivid/elmslie/samples/calculator/StoreTest.kt

1) Make Dispatcher.Default as a main dispatcher
2) Return logging error in actor
3) https://github.com/vivid-money/elmslie/issues/264

Prepare release PART 1

---

elmslie-core/api/elmslie-core.api
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/store/Actor.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/store/ScreenReducer.kt
elmslie-core/src/commonMain/kotlin/money/vivid/elmslie/core/switcher/Switcher.kt

Minor changes, nothing special

Minor changes
